## Atleta [/user]

+ Model (application/json)

    ```js
    {
      "data": {
        "id": "1",
        "type": "athletes",
        "attributes": {
          "name": "Rafael Carvalho",
          "gender": "M",
          "birthday": "1993-08-24",
          "document": "123.123.123-12",
          "phone": "22993214823",
          "avatar": "http://placehold.it/300x300",
          "avatar-from-central": "true"
        },
        "relationships": {
        },
        "links": {
          "self": {
            "href": "http://private-5425b-brlive.apiary-mock.com/api/v3/user"
          }
        }
      },
      "included": [
      ]
    }
    ```