### Listar inscrições [GET]
Um usuário do tipo assessoria tem acesso a várias inscrições num mesmo evento. Portanto essa rota serve para retorna uma lista de recursos do tipo Inscrição que o usuário tem acesso no Evento.

+ Response 200

    [Lista de Inscrições][]