## Lista de Alterações [/user/events/{event_id}/enrollments/{enrollment_id}/versions]
Uma lista de recursos do tipo Version relacionados à Inscrição.

+ Parameters
    + event_id: `23` (string) - O id do Evento.
    + enrollment_id: `24772` (string) - O id da inscrição.

+ Model (application/json)

    ```js
    {
      "data": [
        {
          "id": "2",
          "type": "versions",
          "attributes": {
            "title": "Transferência de inscrição",
            "changes": [
              {
                "old": "Rafael Carvalho",
                "new": "Thawan Fidelis"
              },
              {
                "old": "25 a 30 anos",
                "new": "20 a 25 anos"
              },
              {
                "old": "Geral",
                "new": "Bombeiros"
              }
            ],
            "change-message": "Solicitado por Rafael Carvalho e aceito pela Organização",
            "created_at": "2016-10-24T15:50:07.000-03:00",
            "kind": "enrollment"
          },
          "relationships": {
          },
          "links": {
            "self": {
              "href": "http://http://private-5425b-brlive.apiary-mock.com/api/v3/user/events/23/enrollments/24772/versions/2"
            }
          }
        },
        {
          "id": "1",
          "type": "versions",
          "attributes": {
            "title": "Mudança de faixa etária",
            "changes": [
              {
                "old": "20 a 25 anos",
                "new": "25 a 30 anos"
              }
            ],
            "change-message": "Solicitado por Rafael Carvalho e aceito pela Organização",
            "created_at": "2016-10-23T13:22:07.000-03:00",
            "kind": "age_group"
          },
          "relationships": {
          },
          "links": {
            "self": {
              "href": "http://http://private-5425b-brlive.apiary-mock.com/api/v3/user/events/23/enrollments/24772/versions/1"
            }
          }
        }
      ],
      "included": [
      ],
      "links": {}
    }
    ```