## Lista de Alterações [/user/enrollments/{enrollment_id}/versions]
Uma lista de recursos do tipo Version relacionados à Inscrição.

+ Parameters
    + enrollment_id: `40123` (string) - O id da inscrição.

+ Model (application/json)

    ```js
    {
      "data": [
        {
          "id": "3543",
            "type": "paper-trail-versions",
            "attributes": {
              "item-type": "Enrollment",
              "item-id": 40123,
              "event": "update",
              "created-at": "2016-09-12T10:36:09-03:00",
              "changes": [
              {
                "old": "#4149",
                "new": "#34873"
              }
              ],
              "title": "Mudança de número de peito",
              "change-message": "Editado por Leandro Naves"
            }
        }
      ],
      "links": {}
    }
    ```
